// Code generated by capnpc-go. DO NOT EDIT.

package transport

import (
	capnp "capnproto.org/go/capnp/v3"
	text "capnproto.org/go/capnp/v3/encoding/text"
	schemas "capnproto.org/go/capnp/v3/schemas"
	strconv "strconv"
)

type ConnectRequest capnp.Struct

// ConnectRequest_TypeID is the unique identifier for the type ConnectRequest.
const ConnectRequest_TypeID = 0xb168786247dfb3e7

func NewConnectRequest(s *capnp.Segment) (ConnectRequest, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ConnectRequest(st), err
}

func NewRootConnectRequest(s *capnp.Segment) (ConnectRequest, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return ConnectRequest(st), err
}

func ReadRootConnectRequest(msg *capnp.Message) (ConnectRequest, error) {
	root, err := msg.Root()
	return ConnectRequest(root.Struct()), err
}

func (s ConnectRequest) String() string {
	str, _ := text.Marshal(0xb168786247dfb3e7, capnp.Struct(s))
	return str
}

func (s ConnectRequest) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (ConnectRequest) DecodeFromPtr(p capnp.Ptr) ConnectRequest {
	return ConnectRequest(capnp.Struct{}.DecodeFromPtr(p))
}

func (s ConnectRequest) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s ConnectRequest) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s ConnectRequest) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s ConnectRequest) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s ConnectRequest) ToolName() (string, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.Text(), err
}

func (s ConnectRequest) HasToolName() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s ConnectRequest) ToolNameBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetToolName(v string) error {
	return capnp.Struct(s).SetText(0, v)
}

func (s ConnectRequest) Version() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s ConnectRequest) HasVersion() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s ConnectRequest) VersionBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetVersion(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s ConnectRequest) TaskID() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s ConnectRequest) HasTaskID() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s ConnectRequest) TaskIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s ConnectRequest) SetTaskID(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

func (s ConnectRequest) ProtoVersion() uint32 {
	return capnp.Struct(s).Uint32(0) ^ 1
}

func (s ConnectRequest) SetProtoVersion(v uint32) {
	capnp.Struct(s).SetUint32(0, v^1)
}

// ConnectRequest_List is a list of ConnectRequest.
type ConnectRequest_List = capnp.StructList[ConnectRequest]

// NewConnectRequest creates a new list of ConnectRequest.
func NewConnectRequest_List(s *capnp.Segment, sz int32) (ConnectRequest_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[ConnectRequest](l), err
}

// ConnectRequest_Future is a wrapper for a ConnectRequest promised by a client call.
type ConnectRequest_Future struct{ *capnp.Future }

func (f ConnectRequest_Future) Struct() (ConnectRequest, error) {
	p, err := f.Future.Ptr()
	return ConnectRequest(p.Struct()), err
}

type Chunk capnp.Struct

// Chunk_TypeID is the unique identifier for the type Chunk.
const Chunk_TypeID = 0xce30c8888d8869d3

func NewChunk(s *capnp.Segment) (Chunk, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Chunk(st), err
}

func NewRootChunk(s *capnp.Segment) (Chunk, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3})
	return Chunk(st), err
}

func ReadRootChunk(msg *capnp.Message) (Chunk, error) {
	root, err := msg.Root()
	return Chunk(root.Struct()), err
}

func (s Chunk) String() string {
	str, _ := text.Marshal(0xce30c8888d8869d3, capnp.Struct(s))
	return str
}

func (s Chunk) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Chunk) DecodeFromPtr(p capnp.Ptr) Chunk {
	return Chunk(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Chunk) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}
func (s Chunk) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Chunk) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Chunk) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Chunk) Data() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(0)
	return []byte(p.Data()), err
}

func (s Chunk) HasData() bool {
	return capnp.Struct(s).HasPtr(0)
}

func (s Chunk) SetData(v []byte) error {
	return capnp.Struct(s).SetData(0, v)
}

func (s Chunk) Flush() bool {
	return capnp.Struct(s).Bit(0)
}

func (s Chunk) SetFlush(v bool) {
	capnp.Struct(s).SetBit(0, v)
}

func (s Chunk) End() bool {
	return capnp.Struct(s).Bit(1)
}

func (s Chunk) SetEnd(v bool) {
	capnp.Struct(s).SetBit(1, v)
}

func (s Chunk) Error() (string, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.Text(), err
}

func (s Chunk) HasError() bool {
	return capnp.Struct(s).HasPtr(1)
}

func (s Chunk) ErrorBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(1)
	return p.TextBytes(), err
}

func (s Chunk) SetError(v string) error {
	return capnp.Struct(s).SetText(1, v)
}

func (s Chunk) ContainerID() (string, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.Text(), err
}

func (s Chunk) HasContainerID() bool {
	return capnp.Struct(s).HasPtr(2)
}

func (s Chunk) ContainerIDBytes() ([]byte, error) {
	p, err := capnp.Struct(s).Ptr(2)
	return p.TextBytes(), err
}

func (s Chunk) SetContainerID(v string) error {
	return capnp.Struct(s).SetText(2, v)
}

// Chunk_List is a list of Chunk.
type Chunk_List = capnp.StructList[Chunk]

// NewChunk creates a new list of Chunk.
func NewChunk_List(s *capnp.Segment, sz int32) (Chunk_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 3}, sz)
	return capnp.StructList[Chunk](l), err
}

// Chunk_Future is a wrapper for a Chunk promised by a client call.
type Chunk_Future struct{ *capnp.Future }

func (f Chunk_Future) Struct() (Chunk, error) {
	p, err := f.Future.Ptr()
	return Chunk(p.Struct()), err
}

type Message capnp.Struct
type Message_Which uint16

const (
	Message_Which_connect Message_Which = 0
	Message_Which_chunk   Message_Which = 1
)

func (w Message_Which) String() string {
	const s = "connectchunk"
	switch w {
	case Message_Which_connect:
		return s[0:7]
	case Message_Which_chunk:
		return s[7:12]

	}
	return "Message_Which(" + strconv.FormatUint(uint64(w), 10) + ")"
}

// Message_TypeID is the unique identifier for the type Message.
const Message_TypeID = 0x8cfe5ee0d95f713d

func NewMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func NewRootMessage(s *capnp.Segment) (Message, error) {
	st, err := capnp.NewRootStruct(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1})
	return Message(st), err
}

func ReadRootMessage(msg *capnp.Message) (Message, error) {
	root, err := msg.Root()
	return Message(root.Struct()), err
}

func (s Message) String() string {
	str, _ := text.Marshal(0x8cfe5ee0d95f713d, capnp.Struct(s))
	return str
}

func (s Message) EncodeAsPtr(seg *capnp.Segment) capnp.Ptr {
	return capnp.Struct(s).EncodeAsPtr(seg)
}

func (Message) DecodeFromPtr(p capnp.Ptr) Message {
	return Message(capnp.Struct{}.DecodeFromPtr(p))
}

func (s Message) ToPtr() capnp.Ptr {
	return capnp.Struct(s).ToPtr()
}

func (s Message) Which() Message_Which {
	return Message_Which(capnp.Struct(s).Uint16(0))
}
func (s Message) IsValid() bool {
	return capnp.Struct(s).IsValid()
}

func (s Message) Message() *capnp.Message {
	return capnp.Struct(s).Message()
}

func (s Message) Segment() *capnp.Segment {
	return capnp.Struct(s).Segment()
}
func (s Message) Connect() (ConnectRequest, error) {
	if capnp.Struct(s).Uint16(0) != 0 {
		panic("Which() != connect")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return ConnectRequest(p.Struct()), err
}

func (s Message) HasConnect() bool {
	if capnp.Struct(s).Uint16(0) != 0 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message) SetConnect(v ConnectRequest) error {
	capnp.Struct(s).SetUint16(0, 0)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewConnect sets the connect field to a newly
// allocated ConnectRequest struct, preferring placement in s's segment.
func (s Message) NewConnect() (ConnectRequest, error) {
	capnp.Struct(s).SetUint16(0, 0)
	ss, err := NewConnectRequest(capnp.Struct(s).Segment())
	if err != nil {
		return ConnectRequest{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

func (s Message) Chunk() (Chunk, error) {
	if capnp.Struct(s).Uint16(0) != 1 {
		panic("Which() != chunk")
	}
	p, err := capnp.Struct(s).Ptr(0)
	return Chunk(p.Struct()), err
}

func (s Message) HasChunk() bool {
	if capnp.Struct(s).Uint16(0) != 1 {
		return false
	}
	return capnp.Struct(s).HasPtr(0)
}

func (s Message) SetChunk(v Chunk) error {
	capnp.Struct(s).SetUint16(0, 1)
	return capnp.Struct(s).SetPtr(0, capnp.Struct(v).ToPtr())
}

// NewChunk sets the chunk field to a newly
// allocated Chunk struct, preferring placement in s's segment.
func (s Message) NewChunk() (Chunk, error) {
	capnp.Struct(s).SetUint16(0, 1)
	ss, err := NewChunk(capnp.Struct(s).Segment())
	if err != nil {
		return Chunk{}, err
	}
	err = capnp.Struct(s).SetPtr(0, capnp.Struct(ss).ToPtr())
	return ss, err
}

// Message_List is a list of Message.
type Message_List = capnp.StructList[Message]

// NewMessage creates a new list of Message.
func NewMessage_List(s *capnp.Segment, sz int32) (Message_List, error) {
	l, err := capnp.NewCompositeList(s, capnp.ObjectSize{DataSize: 8, PointerCount: 1}, sz)
	return capnp.StructList[Message](l), err
}

// Message_Future is a wrapper for a Message promised by a client call.
type Message_Future struct{ *capnp.Future }

func (f Message_Future) Struct() (Message, error) {
	p, err := f.Future.Ptr()
	return Message(p.Struct()), err
}
func (p Message_Future) Connect() ConnectRequest_Future {
	return ConnectRequest_Future{Future: p.Future.Field(0, nil)}
}
func (p Message_Future) Chunk() Chunk_Future {
	return Chunk_Future{Future: p.Future.Field(0, nil)}
}

const schema_c0aefe4459d6cfa3 = "x\xdal\x90\xcfk\x13_\x14\xc5\xcf\xb9o\xfa\x9d\xc0" +
	"7\xa1\x192K%(\x0a*T\xe2\x8fUA\x14[" +
	"\x11\x05\xc5\xebBp\xa3N\x93\xa7\x89Ig\x92\x99I" +
	"\xed\xa2\xa5\x0a-\xa4\x90\x82\xb8r\xad{A\xfc\x07\\" +
	"\xba\xd2\x85 \xe8Fw\xfd/22\x09ID\xdc\xbd" +
	"{\xf9<\xce\xe7\x9e\xda\xff\xbc\xe2\x9c+E\x02\xd1#" +
	"\x0b\xffe\x97z\x0f\xbf\xffz0\x1aB\x8bd\xf6\xf6" +
	"\xcb\xb7\xfb\xab\xa3w\x1fq\x8d\xae\x00\x95\xa3|S9" +
	"I\x17\xa8\x1c\xe330;\xfc\xf0\xf3\xfa\xdaf\xf3\xfd" +
	"_\xf4\x82\xc9\x91m\xfe\xa8\xec\x8f\xe1=\x1e\x82\xd9\xd7" +
	"\xd6\xe0`\xf0\xa9\xf6\xf9\x9fp \xaf*-q\x81\x0b" +
	"V\xaa\xc4Rf7l\x98\x9e\xad\x07\xec\x86\xdd\xe5[" +
	"6I\xdc\xe0\x89\xbdCj\xc18\xc5,s\x08x\xa7" +
	"\xaf\x02z\xc2Pk\xc2\x12G\x99\xcf|\xbbt\x1e\xd0" +
	"S\x86zQ\xb8S\x8f\xc2\xd0\xd6S\x96\xe7\xae \xcb" +
	"`\xb5\xde\xec\x87m\x96\xe7Z\x93\xfd,X\xf2\xe0\x95" +
	"\xc9\xf7\xbb\xb6\xd7\xb7&I\xf3\xfc\xb2q\x80q|p" +
	"\x13\xd0G\x86\xda\x11z\xe4$\xbd\x95;5\x0c\xb5+" +
	"\xf4D|\x0a\xe0\xad/\x03\xda4\xd4TH\xe3\xd3\x90" +
	"^\xef)\xa0]C\xdd\x12fi\x14un\x07\xeb\x16" +
	"\x00\x8b\x10\x16\xc1\x9d\x0d\x1b'\xad(\x9c\xce\x97\xd3 " +
	"i\xdfX\x9d\x8eY7\x8e\xd2\xe8\x9e\x8d\xb18\xa6\x0a" +
	"\x10\xaf\xc0?\xfc\xc7\xc5\xad4\xfb!\xdb\xb9\xb6?\xd3" +
	"\xde>\x03\xe8\xa6\xa1\xee\x0a\xa7\xd6/\xf2\xce\xb6\x0cu" +
	"\x90[sb\xbdw\x1c\xd0\xe7\x86:\x14z\x86>\x0d" +
	"\xe0\xed\xe7\xe4\xae\xa1\xbe\x14z\x8e\xf8t\x00\xef`\x0d" +
	"\xd0\xa1\xa1\xbe\x16.6\x824`\x09\xc2\x12X}\xdc" +
	"\xe9'M\x12B\x82\xae\x0d\x1b\xd3w\xd5\xc6q\x14\xcf" +
	"\xae\xa9Ga\x1a\xb4B\x0b7\x9e\xdf\xf8;\x00\x00\xff" +
	"\xffU\xe9\x99\xa2"

func RegisterSchema(reg *schemas.Registry) {
	reg.Register(&schemas.Schema{
		String: schema_c0aefe4459d6cfa3,
		Nodes: []uint64{
			0x8cfe5ee0d95f713d,
			0xb168786247dfb3e7,
			0xce30c8888d8869d3,
		},
		Compressed: true,
	})
}
